### PR TITLE
Fix removing of multiple subscriptions from a join at once

### LINKED ISSUE #16: Endless loop when trying to stop publish worker
You pointed out in the comment in line 31 that this method https://github.com/nlhuykhang/meteor-publish-join/blob/2aece27e075e15ececc4f2c6ca9c3083bb873e83/src/server/worker.js#L21-L34
bares the potential for an endless loop.

Well, I got into it. I'm currently investigating on how this could occur. Please let me know if you are suspecting something or might have a helpful insight here.

### PR DESCRIPTION
**Pull request by SimonSimCity**
The previous code had the chance of removing multiple subscriptions from a single join multiple times, because they had the same subscription-id.

If this is not intended, we should rather switch to a `Set` for storing these elements and then have a different stopping mechanism, but this is at least better than what we had before.

This is a first attempt to fix #16

### CODE REVIEW

**Comment by lmachens** [comment]
So instead of removing all contexts with a _subscriptionId you only remove one. But how do you know that you remove the correct one? Or is that not important?

**Comment by lmachens** [comment]
If I understand it correctly, it is important that all contexts with the _subscriptionId are removed the same time.
Let's take a look at this example:
```
Meteor.publish('test', function(postId) {

  // Publish the number of all comments, re-run every second
  JoinServer.publish({
    context: this,
    name: 'numComments',
    interval: 1000,
    doJoin() {
      return Comment.find().count();
    },
  });

  // Publish the number of likes on a post, re-run every 5 seconds
  JoinServer.publish({
    context: this,
    name: `numLikesOfAPost${postId}`,
    interval: 1000,
    doJoin() {
      // get all likes on post and comments of post
      const value = Post.aggregate([
        // ...
      ]);

      return value[0] && value[0].totalLikes;
    },
  });
});
```

This will create two contexts with the same `_subscriptionId`.
If the subscription ends, it should stop both contexts instead of only one. Otherwise one `JoinServer.publish` would be still active.

Or did I missed something?

**Comment by SimonSimCity** [comment]
In this picture you have two things: The join and the subscription-context. The relation between them is an `[n-n]` relation because every Join can be linked to multiple subscription-contexts (see #2), each identified by the subscription id, and on the other side, a subscription-context can also (as in your example here) register multiple Joins.

Every time you call `JoinServer. publish()` it adds the current subscription-id to that join and also registers a function on `context.onStop()` removing this relation.

As of how I see it, it matches because every time I link up to a join, I also register a destruction event for this relation.

@lmachens I'd be glad if you have the time to double-check if the code matches my description above: https://github.com/nlhuykhang/meteor-publish-join/blob/fcb4f29eaf725ddfc1af082898592b483984263c/src/server/index.js#L106-L122

**Comment by lmachens** [comment]
Thank you for the explaination. Sounds right.

But I do not understand how it is possible that a Join can have multiple `contexts` with the same `_subscriptionId`? It would only be possible if you have a shared join multiple times in a subscription with the same `name`?

**Comment by nlhuykhang** [comment]
I agree with @lmachens, how is it possible that a `Join` (even a shared one) can have multiple `context` with the same `_subscriptionId`? it can only be that a `context` is added more than one time to the same `Join`.

**Comment by SimonSimCity** [comment]
Well, to be quite honest, I don't know. But it was the only explanation I could come up with that would produce an output like I posted in #16. I hope to gain more insights into this when deploying the code of #15 to my production env.

File: src/server/Join.js [hunk 1]
```diff
@@ -66,10 +66,20 @@ export default class Join {
       (now - this._getLastPublishedTime() >= this.interval);
   }
 
-  removeContext({ _subscriptionId }) {
-    this.contexts = this.contexts.filter(
-      context => context._subscriptionId !== _subscriptionId,
-    );
+  _findContextIndex({ _subscriptionId }) {
+    return this.contexts.findIndex(c => c._subscriptionId === _subscriptionId);
```
Comment (nlhuykhang) [inline src/server/Join.js]: _Just a comment, updating not required_
It would be safer if you check for `c` not nullable first. My old code also does not check for that, but overtime I have found that it is generally safer to have a check, because we never what would happen when concurrency involves.

Comment (SimonSimCity) [reply src/server/Join.js]: If we get into real concurrent code (not only callbacks and all the new stuff based on it like promises or async-await), I guess we would have to rethink a lot of code we wrote.

Comment (nlhuykhang) [reply src/server/Join.js]: Yeah, I think more checks for `nullable` values and be careful with the `worker` should be enough

**Comment by SimonSimCity** [comment]
@lmachens @nlhuykhang 

I've added a log in https://github.com/nlhuykhang/meteor-publish-join/issues/16#issuecomment-396909116 which shows that the second call of the Join happens quite some seconds after.

I was not yet able to reproduce this. It could well be tightly connected to the ability of calling `Meteor.subscribe()` reactively - which the `angular-meteor` package chose to have as a built in functionality (https://angular-meteor.com/api/angular-meteor/1.3.11/subscribe). This PR at least provides a working solution for this exceptional case, however it was caused.

@nlhuykhang Please let me know if you're fine with it.

**Comment by SimonSimCity** [comment]
The latest insights and logs shew me that these contexts, which share a common subscription-id, have different connection-ids. I've now added a check to ensure that we're removing the *correct* context from the join. @lmachens, @nlhuykhang  thanks for doubting. I think this is something I have to go to the Meteor guys with ...

**Comment by SimonSimCity** [comment]
@lmachens Today I was able to reproduce it 🎉

See https://forums.meteor.com/t/is-it-by-intention-that-subscription-ids-arent-unique-or-should-subscriptions-be-stopped-before-re-creating-on-a-new-connection/44550

And I now can confirm that this PR would solve both the use case described in the meteor-forum and the use-case where someone (for some reason) would subscribe twice to a shared join within the same subscription using the same unique name (even though I can't come up with a valid reason to do it).

@nlhuykhang Can we merge and release it soon? 😃

**Comment by nlhuykhang** [comment]
@SimonSimCity this is great. Can you fix the unit test that breaks Travis before merging? Please do the same for the other PR too.

What is your npm account? I will add you as collaborator.

**Comment by SimonSimCity** [comment]
@nlhuykhang Thanks! I just created an account 😊My npm username is `simonsimcity`.
